### ISSUE TITLE
Prebuilt binaries

### ISSUE THREAD

**Issue by Decencies** [ergrelet/themida-spotter-bn#3]
It would be useful to have prebuilt binaries included in the repository.

I personally cannot compile it on my machine due to a [compilation error](https://github.com/Vector35/binaryninja-api/issues/5745) related to binary ninja's API.

**Comment by Decencies** [comment]
My apologies the plugin is already listed in the plugins repository.

**Comment by Decencies** [comment]
I am mistaken, that seems to be the unmutate plugin

**Comment by ergrelet** [comment]
Hi!

The error you're getting is most likely due to a version mismatch between the `binaryninja-api` dependency used by the plugin and the version of the binary ninja core lib you have installed.  
I'm currently running on Binary Ninja 4.0.4958 (ddff9339) and it builds fine. Which version are you using?

**Comment by ergrelet** [comment]
Hey!

The DLL is now built on the CI. I added a prebuilt DLL to the last release: https://github.com/ergrelet/themida-spotter-bn/releases/tag/1.0.0
